Eventdjango/Eventdjango/urls.py
from logging import DEBUG
from xml.dom.minidom import Document

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tickets.urls')),
    path('', include('Manage_events.urls')),
] 
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eventdjango/tickets/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
     path('',views.home, name='tickets_home'),
     path('login/',views.my_login, name='tickets_login'),
     path('logout/',views.my_logout, name='tickets_logout'),
     path('signin/',views.sign_in, name='tickets_signin'),
     path('profile/changepassword/',views.change_password, name='tickets_change_password'),
     path('profile/edit/update/<int:user_id>/',views.update_profile, name='tickets_user_update'),
     path('profile/edit/',views.profile, name='tickets_user_profile'),
     path('profile/popularcheck/',views.poppular_check, name='tickets_poppular_check')
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Eventdjango/Manage_events/models.py
from email.policy import default

from django.contrib.auth.forms import UsernameField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
   
    name = models.CharField(max_length=50) 
    

class Event(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    event_name = models.CharField(max_length=20 )
    description = models.TextField()
    event_date = models.DateField( auto_now=False, auto_now_add=False, default = False )
    event_time = models.TimeField()
    location = models.CharField(max_length=200) 
    ticket_price = models.IntegerField(default=0)
    ticket_amount = models.IntegerField(default=0)
    usticket_amount = models.IntegerField( default=0)
    picture = models.ImageField(upload_to='media')
    POPPULAR = (
        ('Yes', 'Yes'),
        ('Not','Not'),
    )
    is_popular = models.CharField( max_length=20, choices=POPPULAR)
    
    

class Ticket(models.Model):
    
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    purchased_date = models.DateField( auto_now=False, auto_now_add=False)

Eventdjango/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% if title %}
       <title>EVENTS-Tickets -{{ title }}</title>
    {% else %}
         <title>EVENTS-Tickets </title>
    {% endif %}
   

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">EVENT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'tickets_home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {%if perms.Manage_events.add_event%}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'eventlist' %}">Manage Event</a>
      </li>{% endif %}
     
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
     <form class="form-inline" method="GET" action="{% url 'search_data' %}">
            
      <input class="form-control mr-sm-2" type="text" placeholder="Search" name ="search"id ="search" value="{{search}}" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      
    </form>
     <ul class="nav justify-content-end">


    
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {% if request.user.username %}
        {{request.user.username}}
    {% else %}
        Login/Signin 
    {% endif %}
     
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.user.username %}
        
          <a class="dropdown-item" href="{% url 'tickets_user_profile' %}">Edit Profile</a>
          <a class="dropdown-item" href="{% url 'tickets_change_password' %}">Change Password</a>
        
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'tickets_logout' %}">Logout</a>
          {% else %}
          <a class="dropdown-item" href="{% url 'tickets_login' %}">Login</a>
          <a class="dropdown-item" href="{% url 'tickets_signin' %}">Sign In</a>
          {% endif %}
        </div>
      </li>
<li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul> 
     
  </div>
</nav>




<div class="container">
 {% block content %}
 {% endblock %}
</div>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Eventdjango/templates/change_password.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Change your password</h1>
        <br/><br/>
        <form method="POST" action="{% url 'tickets_change_password' %}">
        {% csrf_token %}
            <div class="form-group">
                <label for="password1">New password:</label>
                <input type="password" class="form-control ml-3" id="password1" 
                    name="password1" value="{{password1}}">
            </div>
            <div class="form-group">
                <label for="password2">New password (again):</label>
                <input type="password" class="form-control ml-3" id="password2" 
                    name="password2" value="{{password2}}">
            </div>
            <button type="submit" class="btn btn-primary ml-3">Change Password</button>
            {% if error %}
        <p class ="text-danger">{{error}}</p>
       {% endif %}
        </form>
        <br/><br/>
    </div>
{% endblock %}

Eventdjango/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Login to Event</h1>
        <br/><br/>
        {% if error %}
        <p class ="text-danger">{{error}}</p>
       {% endif %}
        <form method="POST" action="{% url 'tickets_login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control ml-3" id="username" 
                    name="username" value="{{username}}">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control ml-3" id="password" 
                    name="password" value="{{password}}">
            </div>
            <button type="submit" class="btn btn-primary ml-3">Login</button>
        </form>
        <br/><br/>
    </div>
{% endblock %}

Eventdjango/templates/sign_in.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <h1>Create New Account</h1>
        <br/>
        
            <!-- Submit to user_add view -->
            <form method="POST" action="{% url 'tickets_signin' %}">
      
        {% csrf_token %}
            {% if msge %}<p class="text-success">{{msge}}</p>{% endif %}
            <div class="form-row">
           
                <div class="form-group col-6">
                    <label for="section">username:</label>
                    <input type="text" class="form-control" name="username" id="username" value="{{user.username}}" required>
                </div>
                 <div class="form-group col-6">
                    <label for="text">password:</label>
                    <input type="text" class="form-control" name="password" id="password" value="{{user.password}}" required>
                </div>
                
                <div class="form-group col-6">
                    <label for="section">ชื่อจริง:</label>
                    <input type="text" class="form-control" name="first_name" id="first_name" value="{{user.first_name}}" required>
                </div>
                <div class="form-group col-6">
                    <label for="section">นามสกุล:</label>
                    <input type="text" class="form-control" name="last_name" id="last_name" value="{{user.last_name}}" required>
                </div>
                
                <div class="form-group col-6">
                    <label for="section">email:</label>
                    <input type="text" class="form-control" name="email" id="email" value="{{user.email}}" required>
                </div>
               
            </div>
            <button type="reset" class="btn btn-warning ml-3">Reset Form</button>
            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </form>
    </div> 
{% endblock  %}

Eventdjango/templates/update_profile.html
{% extends 'base.html' %} {% block content %}
<div class="container">

    <div class="row">
        <div class="col-sm-6" style="background-color:palevioletred;">
            <h1>Profile</h1>

            <br/>

            <!-- Submit to user_add view -->
            {% if user.id %}
            <form method="POST" action="{% url 'tickets_user_update' user_id=user.id %}">

                {% else %}
                <!-- Submit to student_add view -->
                <form method="POST" action="{% url 'tickets_user_profile' %}">
                    {% endif %} {% csrf_token %} {% if msge %}
                    <p class="text-success">{{msge}}</p>{% endif %}
                    <div class="form-row">

                        <div class="form-group col-6">
                            <label for="section">username:</label>
                            <input type="text" class="form-control" name="username" id="username" value="{{user.username}}" required>
                        </div>

                        <div class="form-group col-6">
                            <label for="section">ชื่อจริง:</label>
                            <input type="text" class="form-control" name="first_name" id="first_name" value="{{user.first_name}}" required>
                        </div>
                        <div class="form-group col-6">
                            <label for="section">นามสกุล:</label>
                            <input type="text" class="form-control" name="last_name" id="last_name" value="{{user.last_name}}" required>
                        </div>

                        <div class="form-group col-6">
                            <label for="section">email:</label>
                            <input type="text" class="form-control" name="email" id="email" value="{{user.email}}" required>
                        </div>
                    </div>
                    <button type="reset" class="btn btn-warning ml-3">Reset Form</button>
                    <button type="submit" class="btn btn-primary ml-3">Update</button>
                </form>
        </div>
        <div class="col-sm-6" style="background-color:pink;">
            <p>Ticket You use to Buy</p>
        </div>
    </div>
</div>






{% endblock %}